### ISSUE TITLE
Folder Issue

### ISSUE THREAD

**Issue by TheOnlyDeveloper1620** [KalleHallden/ProjectInitializationAutomation#11]
Hey kalle, How to ask for a different folder each time?

**Comment by lincolnho** [comment]
In the shell script, $1 represents the name of the project. If you want to create the project under a different directory, you can specify the full path in your argument and replace the cd /Users/Kalle/... bit entirely. Then just make the same change in the other files.

**Comment by TheOnlyDeveloper1620** [comment]
Thank you for help...
