### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by nflaig** [KalleHallden/ProjectInitializationAutomation#16]
I created a npm module [github-init-cli](https://www.npmjs.com/package/github-init-cli) which does the same thing but is easier to configure (without source code changes) and also works on properly on windows without using git bash.

To be able to just run `create <name>` instead of `github-init-cli create <name>` the following function could be added to `~/.bashrc`
```bash
function create() {
    github-init-cli create $1
}
```
or if you are using PowerShell on windows add the function to `~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1`
```powershell
function create($name) {
    github-init-cli create $name
}
```

**Comment by String-error-404** [comment]
I have created a same script as this to work on every machine

DO NOT WORRY THIS SCRIPT WORKS ON EVERY MACHINE

Link to the project:
https://github.com/String-error-404/GIT-and-GTITHUB_automation

if you like the project give a star to the repo and follow me on github
